### PR TITLE
Rewrite Activity Bar title also when maximize vertical

### LINKED ISSUE #30: Show title on activity bar for Stacked Windows
When window is maximized, title is shown on Activy bar, but when it's stacked left|right the App name is shown:

screenshot from 2015-06-22 03 47 21
screenshot from 2015-06-22 03 47 34
screenshot from 2015-06-22 03 47 40

The better is to rewrite Activity Titke also when stacked, since the title bar is hidden.

### PR DESCRIPTION
**Pull request by paulodiovani**
This pull request fix #30.

screenshot from 2015-09-05 13 17 37

screenshot from 2015-09-05 13 17 50

### CODE REVIEW

**Comment by FabioBeneditto** [comment]
:+1:

**Comment by deadalnix** [comment]
No. I already looked into this and there no such simple solution. You can have several vertically maximized windows, one on the left and one on the right, and then it becomes very impractical as the controls of visible window become unusable.

**Comment by paulodiovani** [comment]
@deadalnix Yeah. Just noticed that.
I'll try a better solution.

**Comment by paulodiovani** [comment]
@deadalnix Just checked that the same problem occurs when there is two maximized windows. This is possible, one can have many maximized windows and move among the with `Alt + Tab`.

We have to get the currently focused window to rewrite the Activity Bar title.

**Comment by polter-rnd** [comment]
Your patch does not work on latest gnome 3.20 :(
Could you check it out, please?

**Comment by deadalnix** [comment]
This is a different problem that the one in this PR. I often have several maximized window and do not noticed any problems. Can you guys provide repro steps ?

**Comment by polter-rnd** [comment]
@deadalnix sorry, i've confused usernames in previous message, it was addressed to the author of the pull request.

**Comment by paulodiovani** [comment]
I'll look at this sometime forward. Just to busy for now. :(

**Comment by deadalnix** [comment]
Ok I think this is stale and there is no good path forward. Closing.

**Comment by paulodiovani** [comment]
Sorry, @deadalnix.
I'm not using vertical maximized windows for a while, so this change is not necessary for me anymore.

Thanks for closing.

**Pull request closed without merging**
