### PR TITLE
Support gnome 3.26

### PR DESCRIPTION
**Pull request by MichaelAquilina**
Tested on OpenSUSE Tumbleweed

@deadalnix

### CODE REVIEW

**Comment by toXel** [comment]
Please merge this @deadalnix

**Comment by 7adietri** [comment]
Simply adding `3.26` didn't work for me on Ubuntu 17.10. Anything specific I should look at?

**Comment by 7adietri** [comment]
Correction: it does work, but not for all applications, most notably the Terminal. (Also Rhythmbox.)

**Comment by MichaelAquilina** [comment]
The latest Rhythmbox uses CSD (Client Side Decorations) so thats expected. Gnome terminal seems to work for me at the very least. Could you show a screenshot?

**Comment by 7adietri** [comment]
Sure, here's two screenshots:

Terminal:
https://cloud.hamburg.freifunk.net/f/c154c3cf7d8d40baa233/

Firefox:
https://cloud.hamburg.freifunk.net/f/336f5ab66b2a4e16bf54/

The gnome-terminal package on Ubuntu 17.10 is version 3.24.2.

**Comment by franglais125** [comment]
Hey guys, this PR only adds the "advertised" support int he metadata, but it doesn't really change anything code-wise.

In a Wayland session (default for Ubuntu 17.10), it won't work for Wayland-native applications, like the terminal. Firefox works because it uses the Xwayland backend.

If you want this to work for all apps, choose the Xorg session.

Otherwise, have a look at my fork. I have updated it for 3.26, and included some experimental support for Wayland apps as well.

**Pull request merged**
