### PR TITLE
fix for Gnome 3.18

### PR DESCRIPTION
**Pull request by spacepluk**

### CODE REVIEW

**Comment by deadalnix** [comment]
First, thank for your patch. Problem is, 3.8 is still very new and most user are using older version of gnome at this point. This patch remove support for 3.6, which is not desirable at this stage.

If you are willing to, that'd be great to update the patch to include support for both 3.8 and 3.6.

**Comment by spacepluk** [comment]
Hey, no problem :)
How about this?  I haven't tried it on 3.16 but I think it should work.

**Comment by spacepluk** [comment]
Actually, I'm not sure that throws an exception :/

**Comment by spacepluk** [comment]
Nah, it's broken let me give it another try.

**Comment by deadalnix** [comment]
I'm going to try on 3.16 over the week end. If I don't get back fast enough, don't be afraid to ping me.

**Comment by deadalnix** [comment]
Ok looks like it work in 3.16, merging.

**Pull request merged**
