### PR TITLE
Support gnome 3.24

### PR DESCRIPTION
**Pull request by MichaelAquilina**
Tested this out just now on OpenSUSE Tumbleweed and it seems to be working :)

### CODE REVIEW

**Comment by MichaelAquilina** [comment]
That's odd, I wonder why it works for me and not for you. Debugging this would probably help a lot. 

Speaking of which, does anyone know what the correct way to debug gnome extensions is? I cannot figure out how to "run" gnome extensions from source code so that I can print variables / run breakpoints and there doesn't seem to be any documentation available.

**Comment by franglais125** [comment]
@MichaelAquilina , here are a few tips:
To see the log: `sudo journalctl -f /usr/bin/gnome-shell`

Gnome shell extensions are installed in: `.local/share/gnome-shell/extensions/`

You can edit the files in there, adding something like:
```
let myVariable = 0;
global.log("Value of my variable: " + myVariable.toString());
```

So that the value is printed to the log.

**Comment by taaem** [comment]
Found the issue, this extensions needs xprop to be installed otherwise it can't hide the titlebar.

**Comment by MichaelAquilina** [comment]
@deadalnix any update on this?

**Comment by deadalnix** [comment]
Let's go if people tested.

**Pull request merged**
